apiVersion: v2
publisher: lockular
name: cofee
version: 0.0.1
editors:
  - id: eclipse/che-theia/next
    title: Eclipse Theia development version.
    displayName: theia-ide
    description: Eclipse Theia, get the latest release each day.
    icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
    repository: https://github.com/eclipse-che/che-theia
    firstPublicationDate: "2021-01-01"
    endpoints:
      - name: "cstheia"
        public: true
        targetPort: 3000
        attributes:
          protocol: http
          type: ide
          secure: true
          cookiesAuthEnabled: true
          discoverable: false
    containers:
      - name: cstheia-ide
        image: "docker.io/datasignals/coffee-editor:latest"
        mountSources: true
        ports:
          - exposedPort: 3000
        memoryLimit: "512M"
